ESAPI/esapi-java-legacy

src/main/java/org/owasp/esapi/reference/Log4JLogger.java, src/test/java/org/owasp/esapi/reference/Log4JLoggerTest.java
Fixed the problem and created a test to validate it.
https://code.google.com/p/owasp-esapi-java/issues/detail?id=268
=> fix issue 268

src/main/java/org/owasp/esapi/reference/DefaultHTTPUtilities.java, src/test/java/org/owasp/esapi/reference/ValidatorTest.java
Fix for issue #344 	948592a
Using the right AccessControlException class to throw Exception 	db10603
=> Fix some issues

pom.xml, src/test/java/org/owasp/esapi/http/MockHttpServletRequest.java, src/test/java/org/owasp/esapi/http/MockHttpServletResponse.java, src/test/java/org/owasp/esapi/http/MockServletContext.java, src/test/java/org/owasp/esapi/reference/HTTPUtilitiesTest.java, suppressions.xml
=> Suppress CVE-2016-1000031 in dependency check

src/main/java/org/owasp/esapi/Validator.java, src/main/java/org/owasp/esapi/reference/DefaultValidator.java
@kwwall -- This addresses the null check issue.
=> Issue 376 -- Added missed null check on regex pattern.

pom.xml
Update AntiSamy and XOM versions to remove 3rd party vulnerabilities
=> Update antisamy xom

CONTRIBUTING-TO-ESAPI.txt, README.md, pom.xml, src/main/java/org/owasp/esapi/reference/accesscontrol/DelegatingACR.java
Close issue #448 aka, clean-up in aisle 9.
=> Close issue #448

CONTRIBUTING-TO-ESAPI.txt, README.md, pom.xml, src/main/java/org/owasp/esapi/codecs/Base64.java, src/main/java/org/owasp/esapi/configuration/AbstractPrioritizedPropertyLoader.java, src/main/java/org/owasp/esapi/configuration/StandardEsapiPropertyLoader.java, src/main/java/org/owasp/esapi/reference/DefaultSecurityConfiguration.java, src/main/java/org/owasp/esapi/reference/accesscontrol/DelegatingACR.java, src/test/java/org/owasp/esapi/reference/EncoderTest.java
Close issue #385
Close issue #386 
Not done in the way the way that was desired, but output can now be suppressed by setting the `System` property **org.owasp.esapi.logSpecial.discard** to `true`.
=> Log special

.gitignore, pom.xml, src/main/java/org/owasp/esapi/filters/ESAPIFilter.java
I have loaded the project into Eclipse 2018-12 and resolved a maven lifecycle error generated by m2eclipse (comment in pom.xml refers to predecessor q4e) by just updating the plugin version. Also added Eclipse default bin dir to .gitignore.
=> Eclipse setup updates

CONTRIBUTING-TO-ESAPI.txt, README.md, documentation/esapi4java-core-2.2.0.0-release-notes.txt, pom.xml, src/main/java/org/owasp/esapi/AccessController.java, src/main/java/org/owasp/esapi/codecs/CSSCodec.java, src/main/java/org/owasp/esapi/codecs/HTMLEntityCodec.java, src/main/java/org/owasp/esapi/codecs/LegacyHTMLEntityCodec.java, src/main/java/org/owasp/esapi/codecs/MySQLCodec.java, src/main/java/org/owasp/esapi/crypto/CipherText.java, src/main/java/org/owasp/esapi/crypto/CryptoHelper.java, src/main/java/org/owasp/esapi/errors/EnterpriseSecurityException.java, src/main/java/org/owasp/esapi/reference/DefaultAccessController.java, src/main/java/org/owasp/esapi/reference/DefaultEncoder.java, src/main/java/org/owasp/esapi/reference/DefaultHTTPUtilities.java, src/main/java/org/owasp/esapi/reference/DefaultSecurityConfiguration.java, src/main/java/org/owasp/esapi/reference/JavaLogFactory.java, src/main/java/org/owasp/esapi/reference/accesscontrol/ExperimentalAccessController.java, src/main/java/org/owasp/esapi/waf/ConfigurationException.java, src/main/java/org/owasp/esapi/waf/configuration/ConfigurationParser.java, src/main/java/org/owasp/esapi/waf/internal/InterceptingServletOutputStream.java, src/test/java/org/owasp/esapi/filters/SecurityWrapperRequestTest.java, src/test/java/org/owasp/esapi/reference/DefaultSecurityConfigurationTest.java
Thanks to @jeremiahjstacey all tests pass now. Still working on the Dependency Check issues, but let's not let that hold us back. The worst case is we may need to update a few more dependencies.
=> Misc prep issue483

pom.xml, src/main/java/org/owasp/esapi/util/ObjFactory.java, src/test/java/org/owasp/esapi/util/ObjFactoryBenchmark.java
**Before enhance**:
> Benchmark                        Mode  Cnt       Score       Error  Units
> ObjFactoryBenchmark.benchmark1  thrpt   30  337882.228 ±  3149.328  ops/s
> ObjFactoryBenchmark.benchmark2  thrpt   30  279072.632 ± 17234.329  ops/s
**After enhanced**:
> Benchmark                        Mode  Cnt       Score       Error  Units
> ObjFactoryBenchmark.benchmark1  thrpt   30  377886.687 ± 13520.653  ops/s
> ObjFactoryBenchmark.benchmark2  thrpt   30  358412.164 ± 14730.155  ops/s
@kwwall 
Sorry for my carelessness in the previous pull request.
And, the comments is writen in English, but my English is not well. Sorry Again.
=> enhance: improve the performance of ObjFactory

src/main/java/org/owasp/esapi/reference/crypto/JavaEncryptor.java
Close GitHub issue #256 
This looks  like a lot of diffs, but they are all white-space related diffs.
Changed all tabs to the equivalent of spaces, with tabsize set to 4 spaces.
'git diff -w' should should minimal changes. (I think there was few places where tab before '//' comment was changed to spaces, which might show up as a difference.)
=> Close issue #256. White-space clean up.

src/main/java/org/owasp/esapi/Validator.java
DefaultValidator has method documentation, so I'm just copying the
contents verbatim to the interface.
Quick win.
=> Issue #511 Copying Docs from DefaultValidator

src/test/java/org/owasp/esapi/reference/ExecutorTest.java
Creating two tests to assert that the constructor of the DefaultExector
interprets the os.name system property.  If the name contains 'Windows'
the underlying Codec is a WindowsCodec.  If the literal 'Windows' is not
present, then the UnixCodec is applied to the instance.
=> OS Name DefaultExecutorTests #143

documentation/esapi4java-core-2.2.1.0-release-notes.txt
I have no idea how to associate this with Issue #542  but if I figure it out I will do it.
=> Release notes for 2.2.1.0

configuration/esapi/ESAPI.properties, configuration/esapi/esapi-java-logging.properties, src/main/java/org/owasp/esapi/logging/java/JavaLogFactory.java, src/test/java/org/owasp/esapi/logging/java/JavaLogFactoryTest.java, src/test/resources/esapi/ESAPI.properties
Updating the property loading to account for the possible null stream.  Updated exception handling to rethrow ConfigurationException on null stream or IOException from load attempt.
Default content for esapi-java-logging.properties is added to the configuration directory
=> Issue #560 JUL fixes

pom.xml, src/main/java/org/owasp/esapi/codecs/JavaScriptCodec.java, src/main/java/org/owasp/esapi/reference/validation/StringValidationRule.java, src/test/java/org/owasp/esapi/reference/EncoderTest.java, src/test/java/org/owasp/esapi/reference/ValidatorTest.java, src/test/resources/esapi/ESAPI.properties, src/test/resources/esapi/validation.properties
@kwwall @jeremiahjstacey for the moment just try running mvn:test against this.
=> PR to fix #517 and #588

pom.xml
Excluding from Antisamy as transitive
Updating to 1.7.32
Closes #639 #640
=> SLF4J Dependency Updates

pom.xml
=> Updating slf4j-api dependency

pom.xml
https://github.com/nahsra/antisamy/releases/tag/v1.6.5
=> update antisamy to 1.6.5

pom.xml, suppressions.xml
Upgrade a bunch of dependencies and plugins and prepare a bit for the use of AntiSamy 1.6.6.1.
=> Upgrade/cleanup pom and prepare a bit for AntiSamy 1.6.6.1

pom.xml
=> Upgrade to AntiSamy 1.6.6.1 and upgrade a few plugins too.

pom.xml
Updating cyclonedx-maven-plugin to 2.6.0
=> Updating cyclonedx-maven-plugin

src/test/java/org/owasp/esapi/reference/ValidatorTest.java
Contributed on behalf of the @opencastsoftware open source team
=> #702 fix failing unit test on macOS

src/main/java/org/owasp/esapi/ValidationErrorList.java
Fix Javadoc code example in ValidationErrorList #788
=> fixed syntax

.github/ISSUE_TEMPLATE/bug_report.md, scripts/esapi4java-core-TEMPLATE-release-notes.txt, src/main/java/org/owasp/esapi/logging/java/JavaLogFactory.java, src/main/java/org/owasp/esapi/reference/DefaultEncoder.java, src/main/java/org/owasp/esapi/reference/DefaultHTTPUtilities.java, src/test/java/org/owasp/esapi/logging/java/JavaLogFactoryTest.java
=> Whitespace check-in

src/main/java/org/owasp/esapi/Encoder.java, src/main/java/org/owasp/esapi/reference/DefaultEncoder.java, src/test/java/org/owasp/esapi/reference/EncoderTest.java
This commit updates:
* LDAP encoder documentation;
* LDAP encoding in encodeForDN and encodeForLDAP;
* LDAP tests for encodeForDN and encodeForLDAP;
=> Update LDAP encoders

pom.xml, src/main/resources/META-INF/esapi.tld
1. Update pom.xml
2. Update esapi.tld (minor documentation tweaks)
=> Pom updates to address issue #847
