src/main/java/org/owasp/esapi/filters/ClickjackFilter.java
https://github.com/ESAPI/esapi-java-legacy/issues/289
When using ClickJackFilter, In some cases response header is not set.
http://stackoverflow.com/questions/11371755/clickjacking-filter-to-add-x-frame-options-in-response
=> Fix for issue #289

src/test/java/org/owasp/esapi/reference/ValidatorTest.java
PROBLEM
The org.owasp.esapi.errors.ValidationException is thrown with a logMessage:
Invalid date: context=datetest1,
format=java.text.SimpleDateFormat@2aca24a9, input=September 11, 2001
and a detailMessage:
datetest1: Invalid date must follow the java.text.DecimalFormat@674dc
format
CAUSE
The SimpleDateFormat.getDateInstance() is default locale dependent, so
the date September 11, 2001 can't be correctly formatted on my Java Virtual
Machine Locale which is it_IT.
SOLUTION
Use the US locale.
Fixes ESAPI/esapi-java-legacy#345
=> Fixes #345 - JUnit test failure in ValidatorTest.testIsValidDate()

src/main/java/org/owasp/esapi/errors/IntrusionException.java
to know if an uncaught exception is a security exception or usual runtime exception.
=> Fix to Google Issue 212

src/main/java/org/owasp/esapi/waf/internal/InterceptingServletOutputStream.java
Fixes issue 355 by adding tempFile.deleteOnExit() in InterceptingServletOutputStream.
This only works for a clean vm exit.
If robustness is required I can redo it following the implementation  [here](http://stackoverflow.com/questions/16691437/when-are-java-temporary-files-deleted/16694493#16694493)
=> Fix issue 355 by adding a call to file.deleteOnExit().

pom.xml
This PR attempts to close #361.
```
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Building ESAPI 2.1.0.1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- versions-maven-plugin:2.2:display-plugin-updates (default-cli) @ esapi ---
[INFO] 
[INFO] All plugins with a version specified are using the latest versions.
[INFO] 
[INFO] All plugins have a version specified.
[INFO] 
[INFO] Project defines minimum Maven version as: 3.0
[INFO] Plugins require minimum Maven version of: 3.0
[INFO] 
[INFO] No plugins require a newer version of Maven than specified by the pom.
[INFO] 
[INFO] Require Maven 3.0.1 to use the following plugin updates:
[INFO] …
```
=> Update pom.xml to use latest Maven plugins

pom.xml
```
<resources>
<resource>
<directory>configuration/META-INF</directory>
<targetPath>META-INF</targetPath>
</resource>
</resources>
```
The above packages all files in `configuration/META-INF`  (currently only esapi.tld) to the `META-INF` dir in jar file.
This however, causes files in `src/main/resources` (ESAPI-properties.xsd) to be ignored.
```
<resources>
<resource>
<directory>src/main/resources</directory>
</resource>
<resource>
<directory>configuration/META-INF</directory>
<targetPath>META-INF</targetPath>
</resource>
</resources>
```
The above fixes issue #365 and all related issues.
=> Packages the esapi.tld into the jar file.

src/main/java/org/owasp/esapi/Validator.java, src/main/java/org/owasp/esapi/reference/DefaultValidator.java, src/test/java/org/owasp/esapi/reference/ValidatorTest.java, src/test/resources/urisForTest.txt
> Matt,
>
> As promised; sorry I didn't get to this earlier. I will be gone remainder of
> today and tomorrow so if you have questions they may not get answered
> until Tuesday.
>
> Anyway, just a few minor comments. While they look numerous, this is probably
> only a 1/2 or so of clean-up, so it's not as bad as it looks. But overall,
> looks solid. Thanks for the contribution.
>
> Validator.java - looks good. Maybe just add a hypertext link in the Javadoc for
>     RFC 3986 to the IETF RFC page.
>
> DefaultValidator.java -
>     1) Maybe add your name as author? (We all know you touched it last
> anyhow!  :)
Done.  Will be in next commit.  
…
>     2) in isValidURI(), if 'allowNull' is 'true' and 'input' is null, then
>        unless I'm missing something, I don't think this does what …
=> Issue #376 -- Addressed Kevin Wall's CR comments.

src/main/java/org/owasp/esapi/Encoder.java, src/main/java/org/owasp/esapi/reference/DefaultEncoder.java, src/test/java/org/owasp/esapi/reference/EncoderTest.java
Overloaded the encodeForLDAP method to provide the option of not
encoding wildcard (*) characters.
This would be used when doing queries against an LDAP directory using
wildcards, while at the same time, encoding other potentially dangerous
characters.
=> Issue #389

src/main/java/org/owasp/esapi/filters/SecurityWrapperResponse.java, src/main/java/org/owasp/esapi/reference/DefaultHTTPUtilities.java
The DefaultHttpUtilities and SecurityWrapperResponse add systematically a Max-Age to the HTTP Header when adding a cookie. Even if the cookie has a negative maxAge value (which is the default value).
So when adding a "session" cookie (without Max-Age), ESAPI add a Max-Age=-1 in the HTTP Header and the cookie will be discarded by the browser, because it is invalid (http://www.ietf.org/rfc/rfc2109.txt).
Wen the maxAge field of the cookie is negative, it should not be specified at HTTP Header level.
=> Support of Cookie without maxAge set

src/main/java/org/owasp/esapi/codecs/HTMLEntityCodec.java
HTMLEntityCodec.decode incorrectly decodes upper-case accented letters as their lower-case counterparts. In this change i am doing an exact match for the possible string and if the match is not found falling back to the old technique of lowercasing the possible string & find a match for it. Please review this change
=> #302 HTMLEntityCodec Now decodes cased accented letters properly

pom.xml, src/main/java/org/owasp/esapi/reference/DefaultSecurityConfiguration.java
The existing code uses enum names instead of the values to try to load ESAPI.properties.
=> Fix configuration loading: Use value instead of constants also update vulnerable dependencies

src/main/java/org/owasp/esapi/reference/DefaultEncoder.java
Fixed the encoderForLDAP method to use a "switch" statement as was suggested by the maintainer.
=> Fixed the encoderForLDAP method to use a "switch" statement as was suggested by the maintainer.

pom.xml
Details:
Update <targetJdk> for PMD plugin from 1.5 to 1.7
Update version for <requireJavaVersion> for maven-enforcer-plugin from 1.6 to 1.7
Update batik from 1.9 to 1.9.1
Add test dependency for Bouncy Castle 1.58 (only required for JUnit tests)
Added some compiler flags (warnings) for CII Badging effort
Update version of Dependency Check used to 2.1.0
Update maven-javadoc-plugin to 3.0.0-M1
Update commons-io from 2.5 to 2.6 (only used for JUnit tests)
=> Close issue #429.

configuration/esapi/ESAPI.properties, src/main/java/org/owasp/esapi/reference/DefaultSecurityConfiguration.java, src/test/java/org/owasp/esapi/reference/ValidatorTest.java, src/test/resources/esapi/ESAPI-CommaValidatorFileChecker.properties, src/test/resources/esapi/ESAPI-DualValidatorFileChecker.properties, src/test/resources/esapi/ESAPI-QuotedValidatorFileChecker.properties, src/test/resources/esapi/ESAPI-SingleValidatorFileChecker.properties, src/test/resources/esapi/ESAPI.properties
Changed HttpUtilities.ApprovedUploadExtensions to proposed defaults as discussed in issue #439 and updated code and JUnit tests accordingly.
=> Close #439 by racheting down default allowed file suffixes used with file uploads

pom.xml, src/test/java/org/owasp/esapi/reference/crypto/EncryptorTest.java
1. Updated BC from 1.58 to 1.60
2. Relax JUnit test assertion so that encoded key size is >= to requested key size instead of equal to requested key size.
=> Close #438 by loosening JUnit test case assertion

src/test/java/org/owasp/esapi/reference/AuthenticatorTest.java
Several changes that appear to improve the stability of the overall test.
First, broke testSetCurrentUserWithRequest into five uniquely named tests.
One of these is used to verify a user with an expired account cannot log
in.  Fix here is to explicitly set the expiration time in the past to
prevent the implementation from validating in the same millisecond.
Second, updated the internal runnable in testSetCurrentUser to generate a
more complex password.  Found that the previous password would
occasionally fail the FileBasedAuthenticator password strength check. I
assumed it was because the strength value was being calculated as either 8
or 16.  Stregth would evaluate to 8 if the 8-character string was composed
of only one unique type of character (upper/lower/number/special), 16 if
there …
=> AuthenticatorTest Stability #360

src/main/java/org/owasp/esapi/reference/AbstractAccessReferenceMap.java, src/test/java/org/owasp/esapi/reference/AbstractAccessReferenceMapTest.java
Potential resolutions for two issues in AbstractAccessReferenceMap.
First, handling #329 I've provided a multi-threaded unit test which replicates the condition consistently.  The offered solution is to add *synchronized* keyword to all public API of the AbstractAccessReferenceMap.
Second, #37 Provided a test which shows that in cases where subclasses return the same indirect key multiple times it can lead to corruption during update.  Logic updates were made to the implementation to address.
=> AbstractAccessReferenceMap Issues #37 #329

src/main/java/org/owasp/esapi/reference/JavaLogFactory.java, src/test/java/org/owasp/esapi/reference/JavaLogFactoryTest.java
Possible solution to Issue #286 to test and resolve the thread safety concerns of creating JavaLog references.
=> JavaLogFactory Thread Safety #286

pom.xml, src/main/java/org/owasp/esapi/ValidationErrorList.java, src/main/java/org/owasp/esapi/reference/DefaultValidator.java, src/main/java/org/owasp/esapi/reference/validation/DateValidationRule.java, src/test/java/org/owasp/esapi/ESAPIContractAPITest.java, src/test/java/org/owasp/esapi/ValidationErrorListTest.java, src/test/java/org/owasp/esapi/reference/DefaultValidaterDateAPITest.java, src/test/java/org/owasp/esapi/reference/ValidatorTest.java, src/test/java/org/owasp/esapi/reference/validation/BaseValidationRuleTest.java, src/test/java/org/owasp/esapi/reference/validation/DateValidationRulePowerMockTest.java, src/test/java/org/owasp/esapi/reference/validation/DateValidationRuleTest.java
These commits offer a possible solution to issue #299.
Summary of changes:
* DateValidationRule API extended to include a new sanitize method which accepts a ValidationErrorList
* DefaultValidator updated to use the DateValidationRule sanatize method
* Tests around implementation including sample strings from 299 and 258
The changes to DateValidationRule make a distinction between the getValid and sanitize API's.  getValid will make the best possible effort, given configuration and formatter, to determine if any date can be parsed from the input string with no guarantee of safety or accuracy of the input.  This route relies soley on the backing DateFormat for success.
sanitize extends the getValid behavior by attempting validate that the input can be considered 'safe' for application use.
=> Date validation rule 299

src/test/java/org/owasp/esapi/filters/SecurityWrapperRequestTest.java, src/test/java/org/owasp/esapi/reference/DefaultValidatorInputStringAPITest.java
Issue 188 is already functionally complete in the current baseline.  These changes are only test updates for each of the elements in the current workflow to show that each propagates information as desired.
Summary of changes:
Tests added to the SecurityWrapperRequestTest to show that the arguments provided to the wrapper are forwaded to the configured Validator instance.
ESAPIContractAPITest already exists and shows that the ESAPI lookup does return the expected configuration instance for the Validator lookup.
The tests DefaultValidatorInputStringAPITest were added to assert the passthrough behavior of the isValidInput and getValidInput methods of the DefaultValidator.  Note that the -canonicalize- variable to the getValidInput API was not tested, as it is never used and only exists in …
=> Issue #188 resolution proof:  Test updates

src/main/java/org/owasp/esapi/reference/DefaultValidator.java, src/main/java/org/owasp/esapi/reference/validation/StringValidationRule.java, src/test/java/org/owasp/esapi/reference/DefaultValidatorInputStringAPITest.java, src/test/java/org/owasp/esapi/reference/validation/StringValidationRuleTest.java
Implementation and test updates consistent with the recommended approach.  StringValidationRule behavior for canonicalization is now configurable & DefaultValidator uses that configuration when evaluating a valid String input.
Tests updated to match expectations.
=> #476 DefaultValidator.getValidInput uses canonicalize method argument

src/main/java/org/owasp/esapi/Randomizer.java
Added the documentation for the method referenced in #226
Also added documentation for getRandomReal(float,float) so it is not left ambiguous
Although the original issue does not mention getRandomReal, I thought it would be appropriate to add the documentation there as well for additional clarity. As a developer, seeing the documentation on getRandomInteger could cause confusion about the behavior of getRandomReal.
=> Resolves #226 - Corrected docs for the  bounded, numeric, random methods

pom.xml
Close issue #512 and any Java deserialization vulnerabilities that might present themselves as a result. (Note that regarding the BeanUtils commit, the fix was in org.apache.commons.beanutils2.PropertyUtilsBean. Based on a cursory examination, the ESAPI team does not believe that this vulnerability reported by Snyk was exploitable given that manner that it is used within ESAPI, or if it is, it is not externally exploitable based on the default access control rules that are provided with ESAPI. However, to be prudent and patching it seems to be the wise course if for no other reason, it will make Snyk shut up! :)
=> Close issue #512 by updating to 1.9.4 of Commons Beans Util.

src/main/java/org/owasp/esapi/codecs/CSSCodec.java, src/main/java/org/owasp/esapi/codecs/ref/EncodingPatternPreservation.java, src/test/java/org/owasp/esapi/codecs/CSSCodecTest.java, src/test/java/org/owasp/esapi/codecs/ref/EncodingPatternPreservationTest.java, src/test/java/org/owasp/esapi/reference/EncoderTest.java
@xeno6696  I think this achieves the capability you were looking for with Issue 494.  I have not worked much with the expectations of the Codec API so please let me know if I'm missing something.
As an aside, I did try to build the regex replacement capability as a separate class instance.  In future cases like this we may just need to figure out the regex and inject this piece into the process.
The new test cases pass, but I am currently seeing an issue with ValidatorTest.testIsValidSafeHTML and ValidatorTest.testGetValidSafeHTML.  I've verified that I am seeing the same failures across my fork of the develop branch.
=> Issue 494 CSSCodec RGB Triplets

pom.xml
I have seen the commented text next to `powermock-api-mockito2` dependency in [pom.xml](https://github.com/ESAPI/esapi-java-legacy/blob/develop/pom.xml#L322) and I assume that we would like to have 100% convergence.
This pull request adds a rule for `maven-enforcer-plugin` that checks that.
I needed to upgrade `powermock-reflect` from 2.0.0 to 2.0.2 (didn't check if that works with JAVA 7).
I also merged two executions of the plugin into one:
1. if there is only one execution then the *id* is not needed
1. `<fail>` parameter for this plugin has **true** as default value
=> upgrade for convergence

src/main/java/org/owasp/esapi/reference/DefaultSecurityConfiguration.java, src/test/java/org/owasp/esapi/crypto/CryptoTokenTest.java, src/test/java/org/owasp/esapi/reference/ExtensiveEncoderURITest.java
This pull request contain changes for building the project in folder that contains spaces.
See also issue https://github.com/ESAPI/esapi-java-legacy/issues/382.
`URI` used instead of `URL` (see https://stackoverflow.com/a/13470643).
I believe the `DefaultSecurityConfiguration#getResourceFile` could be further improved, but that should be probably part of another pull request, or maybe even part of version 3.x...
=> Issue 382: Build Fails on path with space

configuration/esapi/ESAPI.properties, src/main/java/org/owasp/esapi/SecurityConfiguration.java, src/main/java/org/owasp/esapi/reference/DefaultSecurityConfiguration.java, src/main/java/org/owasp/esapi/reference/validation/HTMLValidationRule.java, src/test/java/org/owasp/esapi/reference/validation/HTMLValidationRuleClasspathTest.java, src/test/java/org/owasp/esapi/reference/validation/HTMLValidationRuleCleanTest.java, src/test/java/org/owasp/esapi/reference/validation/HTMLValidationRuleThrowsTest.java, src/test/resources/antisamy-esapi-CP.xml
I delegated loading from the class path to SecurityConfiguration because all the directory configurations are there.
The private method loadConfigurationFromClasspath from DefaultSecurityConfiguration could reuse that method, but I didn't dare to change that on short notice.
HJW8472
=> Fixed issue #310

src/main/java/org/owasp/esapi/Logger.java, src/main/java/org/owasp/esapi/logging/java/ESAPICustomJavaLevel.java, src/main/java/org/owasp/esapi/logging/java/ESAPIErrorJavaLevel.java, src/main/java/org/owasp/esapi/logging/java/JavaLogFactory.java, src/main/java/org/owasp/esapi/logging/java/JavaLogLevelHandlers.java, src/test/java/org/owasp/esapi/logging/java/JavaLogLevelHandlersTest.java
https://github.com/ESAPI/esapi-java-legacy/issues/571#issuecomment-691674605
Adding implementation noted in the comment listed above.
Caveat to this implementation is that if the Java Logging configuration is set to OFF then no logging will occur.  I don't think there's much that can be done about this particular use case.
=> Issue 571: JavaLogFactory ALWAYS

configuration/esapi/ESAPI.properties, pom.xml, src/main/java/org/owasp/esapi/SecurityConfiguration.java, src/main/java/org/owasp/esapi/reference/DefaultSecurityConfiguration.java, src/main/java/org/owasp/esapi/waf/configuration/AppGuardianConfiguration.java, src/main/java/org/owasp/esapi/waf/configuration/ConfigurationParser.java, src/test/java/org/owasp/esapi/SecurityConfigurationWrapper.java, src/test/java/org/owasp/esapi/reference/DefaultSecurityConfigurationTest.java, src/test/resources/esapi/ESAPI-CommaValidatorFileChecker.properties, src/test/resources/esapi/ESAPI-DualValidatorFileChecker.properties, src/test/resources/esapi/ESAPI-QuotedValidatorFileChecker.properties, src/test/resources/esapi/ESAPI-SingleValidatorFileChecker.properties, src/test/resources/esapi/ESAPI.properties
Issue #593 really isn't a bug in ESAPI, but id did reveal some significant understandings regarding ESAPI logging and how it is controlled.
The purpose of this PR is to try to clear up some of that confusion that is caused by old methods and properties that were never actually implemented to do what was expected, but that was documented (in both Javadoc and the ESAPI.properties files).
=> Address latent confusion caused by obsolete / deprecated ESAPI methods related to Issue #593

pom.xml, src/main/java/org/owasp/esapi/configuration/XmlEsapiPropertyLoader.java
Upgrade a few libraries, add some used but undeclared libraries, and delete a bunch of declared/unused libraries. Also upgrade a bunch of plugins, and add support for using newer versions of SpotBugs even if the maven spotbugs plugin is a few versions behind the latest version of SpotBugs. Currently they are both at 4.2.2 but that isn't always the case.
This also addresses issue #614, by setting the proper security setting on an XML Parser Factory to disable an on-by-default feature that could allow an XXE exploit, but only from an insider attack against the ESAPI configuration file. While very unlikely, figured it's best to fix anyway. The referenced issue was opened after the pull request was created :-).
=> Suggested pom.xml updates and XmlEsapiPropertyLoader.java improvements

src/main/java/org/owasp/esapi/logging/java/JavaLogger.java, src/main/java/org/owasp/esapi/logging/log4j/Log4JLogger.java, src/main/java/org/owasp/esapi/logging/slf4j/Slf4JLogger.java, src/test/java/org/owasp/esapi/logging/java/JavaLoggerTest.java, src/test/java/org/owasp/esapi/logging/log4j/Log4JLoggerTest.java, src/test/java/org/owasp/esapi/logging/slf4j/Slf4JLoggerTest.java
Closes #630 
Tests updated to reflect desired results of `isEnabled` for each of the loggers.
Logic updated to inverse the evaluate such that the method parameter must be greater than or equal to the configured logging level.
The field `maxLogLevel` has been renamed to `loggingLevel`
=> Logger Level Logic Updates

configuration/esapi/ESAPI.properties, documentation/esapi4java-core-2.0-symmetric-crypto-user-guide.html, src/main/java/org/owasp/esapi/SecurityConfiguration.java, src/main/java/org/owasp/esapi/crypto/CipherText.java, src/main/java/org/owasp/esapi/reference/DefaultSecurityConfiguration.java, src/main/java/org/owasp/esapi/reference/crypto/JavaEncryptor.java, src/test/java/org/owasp/esapi/SecurityConfigurationWrapper.java, src/test/java/org/owasp/esapi/crypto/CipherSpecTest.java, src/test/java/org/owasp/esapi/reference/DefaultSecurityConfigurationTest.java, src/test/resources/esapi/ESAPI-CommaValidatorFileChecker.properties, src/test/resources/esapi/ESAPI-DualValidatorFileChecker.properties, src/test/resources/esapi/ESAPI-QuotedValidatorFileChecker.properties, src/test/resources/esapi/ESAPI-SingleValidatorFileChecker.properties, src/test/resources/esapi/ESAPI.properties
@xeno6696 or @jeremiahjstacey -- these changes are not really as much crypto-related (other than the _reason_ why I'm making them), as the are related to the ESAPI `SecurityConfiguration` component.
I originally had them in the otherwise small updates to prep the next release (which I am actually going to call 2.3.0.0 rather than 2.2.4.0, so I can finally justify dumping this whole bad "fixed IV" idea. (Thought up in the days where I was emphasizing backward compatibility and supporting legacy code over security, Sigh. Well, guess that means I learned _something_ in the past 10 plus years.)
Anyhow, could I get one of you to do a quick and dirty code review and them merge this? Pending my email to Sebastian and Dave, I'd like to get this merged by early tomorrow evening so I can get it …
=> Changes to close issue #679

pom.xml, src/main/java/org/owasp/esapi/Encoder.java, src/main/java/org/owasp/esapi/SecurityConfiguration.java, src/main/java/org/owasp/esapi/codecs/AbstractCodec.java, src/main/java/org/owasp/esapi/codecs/Codec.java, src/main/java/org/owasp/esapi/codecs/JavaScriptCodec.java, src/main/java/org/owasp/esapi/codecs/UnixCodec.java, src/main/java/org/owasp/esapi/crypto/CipherText.java, src/main/java/org/owasp/esapi/filters/ClickjackFilter.java, src/main/java/org/owasp/esapi/reference/DefaultEncoder.java, src/main/java/org/owasp/esapi/reference/DefaultSecurityConfiguration.java, src/test/java/org/owasp/esapi/reference/EncoderTest.java, src/test/java/org/owasp/esapi/reference/ExecutorTest.java
Close #686. Close #689
LOTS of Javadoc clean-up and corrections.
=> Issues 686 & 689 - Create DefaultEncoder from Encoder.DefaultCodecList and Javadoc clean-up

pom.xml
Closes #690 
```
maven-project-info-reports-plugin .................. 3.2.2 -> 3.3.0
maven-site-plugin .............................. 3.12.0 -> 4.0.0-M1
com.github.spotbugs:spotbugs-annotations .............. 4.6.0 -> 4.7.0
com.github.spotbugs:spotbugs .......................... 4.6.0 -> 4.7.0
```
`mvn clean package` and `mvn site:site` complete successfully
=> Plugin & Dependency Updates

src/main/java/org/owasp/esapi/Validator.java, src/main/java/org/owasp/esapi/reference/DefaultValidator.java
Contributed on behalf of the @opencastsoftware open source team
This was larger than I initially expected. I have generated the javadoc for the two classes and read through it a couple of times, but I'm concerned I may have missed something obvious.
=> #674 expand Validator interface Javadoc based on DefaultValidator

src/main/java/org/owasp/esapi/reference/DefaultValidator.java
This is to address Issue #705. Only Javadoc changes.
@xeno6696, @jeremiahjstacey, and maybe @stevebosman-oc -- please take a look at the changes to make sure they are clear. Thanks.
=> Issue 705 - Additional Javdoc for DefaultValidator class

pom.xml, src/examples/java/PersistedEncryptedData.java, src/main/java/org/owasp/esapi/PropNames.java, src/main/java/org/owasp/esapi/crypto/KeyDerivationFunction.java, src/main/java/org/owasp/esapi/errors/EnterpriseSecurityException.java, src/main/java/org/owasp/esapi/logging/java/JavaLogFactory.java, src/main/java/org/owasp/esapi/logging/log4j/Log4JLogFactory.java, src/main/java/org/owasp/esapi/logging/log4j/Log4JLoggerFactory.java, src/main/java/org/owasp/esapi/logging/slf4j/Slf4JLogFactory.java, src/main/java/org/owasp/esapi/reference/DefaultSecurityConfiguration.java, src/main/java/org/owasp/esapi/reference/validation/HTMLValidationRule.java, src/main/java/org/owasp/esapi/waf/configuration/AppGuardianConfiguration.java, src/test/java/org/owasp/esapi/filters/SecurityWrapperRequestTest.java, src/test/java/org/owasp/esapi/filters/SecurityWrapperResponseTest.java, src/test/java/org/owasp/esapi/reference/DefaultSecurityConfigurationTest.java, src/test/java/org/owasp/esapi/reference/validation/DateValidationRuleTest.java, src/test/java/org/owasp/esapi/reference/validation/HTMLValidationRuleClasspathTest.java, src/test/java/org/owasp/esapi/reference/validation/HTMLValidationRuleCleanTest.java, src/test/java/org/owasp/esapi/reference/validation/HTMLValidationRuleThrowsTest.java
@xeno6696 and @jeremiahjstacey - I didn't address the stuff in the email yet about `getDisableIntrusionDetection()` yet, but OTOH, I didn't un-deprecate it, so we still have time to work on that as there still are a bunch of deprecations to deal with besides that one. I just didn't want to spend ALL holiday working on this so not going to let the perfect become the enemy of the good here.
=> Issue 620 - Move public static final Strings and enum from DefaultSecurityConfiguration to PropNames

documentation/LoggerDesignAndTesting.md, pom.xml, scripts/esapi-release.sh, scripts/esapi4java-core-TEMPLATE-release-notes.txt, src/examples/java/DisplayEncryptedProperties.java, src/examples/java/ESAPILogging.java, src/examples/scripts/encryptProperties.sh, src/examples/scripts/persistEncryptedData.sh, src/examples/scripts/runClass.sh, src/examples/scripts/setMasterKey.sh, src/examples/scripts/setenv-svn.sh, src/examples/scripts/setenv-zip.sh, src/main/assembly/dist.xml, src/main/java/org/owasp/esapi/Logger.java, src/main/java/org/owasp/esapi/waf/ESAPIWebApplicationFirewallFilter.java, src/test/java/org/owasp/esapi/reference/TestDebug.java, src/test/java/org/owasp/esapi/reference/TestError.java, src/test/java/org/owasp/esapi/reference/TestFatal.java, src/test/java/org/owasp/esapi/reference/TestInfo.java, src/test/java/org/owasp/esapi/reference/TestTrace.java, src/test/java/org/owasp/esapi/reference/TestUnspecified.java, src/test/java/org/owasp/esapi/reference/TestWarning.java, src/test/java/org/owasp/esapi/waf/WAFTestUtility.java
In preparation for the ESAPI 2.5.0.0 release, which primarily addresses the removal of the Log4J 1 dependency for ESAPI logging (which has been deprecated for almost 2 years), this PR does the following:
1. Removes the final (non-documentation) vestiges of Log4J. Mostly was left in examples under 'src/examples', scripts under 'scripts' and in various comments. I did not remove it from documentation because of historical needs (e.g., people needing to look at old release notes or security bulletins).
2. Update pom.xml to use latest dependencies and Maven plugins. (Note: The official release of AntiSamy 1.7.0 is not yet in Maven Central, but we will upgrade to that once it is.)
Note that this PR does NOT include the release notes for 2.5.0.0.
=> Log4j loose ends

src/main/java/org/owasp/esapi/configuration/EsapiPropertyLoaderFactory.java
It was asked to change the message given by an exception in the EsapiPropertyLoaderFactory Class that specified that only .xml files or .properties files were allowed. 
So, using a user-friendly approach, I decided to call the ending of the file an "extension" and told in the message that only files with the  .xml or .properties "file extension" were supported.
=> Issue#735 ConfigurationException message changed to a more intuitive one

src/main/java/org/owasp/esapi/logging/java/JavaLogFactory.java, src/test/java/org/owasp/esapi/logging/java/JavaLogFactoryTest.java
Closes #710 
Updating JUL to check for existing global LogManager configuration prior to applying ESAPI file settings.
Adding tests to verify LogManager Configurations are preferred to the ESAPI configurations.
=> Issue 710 JUL Respect LogManager Config

src/main/java/org/owasp/esapi/Encoder.java, src/main/java/org/owasp/esapi/codecs/AbstractCodec.java, src/main/java/org/owasp/esapi/codecs/AbstractIntegerCodec.java, src/main/java/org/owasp/esapi/codecs/HTMLEntityCodec.java, src/main/java/org/owasp/esapi/codecs/JSONCodec.java, src/main/java/org/owasp/esapi/reference/DefaultEncoder.java, src/test/java/org/owasp/esapi/reference/EncoderTest.java
This commit adds JSON string escaping support according to RFC 8259, Section 7.
See GitHub Issue 
closes #754. [added by @kwwall]
=> JSON string escaping support

pom.xml
Closes #733 
> Replacing:
>   net.sourceforge.maven-taglib:maven-taglib-plugin:2.4
> with
>  io.github.weblegacy:taglib-maven-plugin:2.6
[taglib-maven-plugin](https://search.maven.org/artifact/io.github.weblegacy/taglib-maven-plugin/2.6/maven-plugin)
To verify:
```
]$ git clone https://github.com/jeremiahjstacey/esapi-java-legacy-dev.git ./PR-taglib-docs
]$ cd PR-taglib-docs
]$ mvn site:site
]$ firefox target/site/index.html &
```
1. Three new taglib headings are listed
2. Each tab is selectable
3. When selected, each tab renders unique content about the taglib context for the project.
Expected index.html Display
----
=> Site Taglib Documentation

src/main/java/org/owasp/esapi/logging/appender/ServerInfoSupplier.java, src/test/java/org/owasp/esapi/logging/appender/ServerInfoSupplierTest.java
**I have recreated PR #772, except this time I have properly signed the commit.**
This change deals with issue #767.
It does not attempt to resolve the overall issue with Servlet API version compatibility. What it does is remove the dependency on Servlet API for the use case where a user is trying to use the logger functionality, but has "logServerIP" set to false. When not logging the server IP, there is no reason for this code to depend on Servlet API at all.
This allows us to avoid runtime exceptions if we use this code with the new Jakarta package version of Servlet API, in cases where logServerIP is disabled.
Again, this is not a fix for the overall problem. This is a small change that will let some limited use cases not fail due to the problem (so that those use cases can get by …
=> remove dependency on servlet API (use case where not needed)

.gitignore, pom.xml, src/site/site.xml
Fix fluido skin version inheritance from pom to src/site/site.xml file. And upgrade a number of plugins and maybe one library. Fix some used undeclared and unused declared imports.
=> Fix fluido skin plugin version inheritance from pom to src/site/site.xml

.gitignore, pom.xml
This PR adds a Maven profile called "jakarta" that will generate a transformed JAR file, compatible with the `jakarta.servlet` changes for Jakarta EE 9+
I don't know how you public packages, and I doubt this is a full solution, but it at least gets you pointed in the right direction.
=> Using Eclipse Transformer plugin to create Jakarta JAR

pom.xml, src/test/java/org/owasp/esapi/reference/validation/HTMLValidationRuleCleanTest.java
This is to resolve CVE-2024-23635 relating to Antisamy 1.7.4.
It's related and similar to https://github.com/ESAPI/esapi-java-legacy/pull/830, however it resolves dependency conflicts and updates 2 test cases as the output we get from Antisamy looks a bit different. I think this is to be expected: as mentioned in the [release notes](https://github.com/nahsra/antisamy/releases/tag/v1.7.5) for Antisamy 1.7.5 the output may have changed again:
> Note: The upgrade in the HTML parser may alter outputs compared to 1.7.4 and before. This may impact regression tests that involve AntiSamy if they are too strict when comparing a resulting output with the expected one.
Also related to: https://github.com/nahsra/antisamy/issues/389 and https://github.com/nahsra/antisamy/pull/388.
=> fix: upgrade Antisamy to 1.7.5 to resolve CVE-2024-23635

configuration/esapi/esapi-java-logging.properties, src/main/java/org/owasp/esapi/logging/java/JavaLogFactory.java, src/test/java/org/owasp/esapi/logging/java/JavaLogFactoryTest.java, src/test/resources/esapi-java-logging.properties
Removing support for esapi-java-logging.properties file from baseline.
ConfigurationException is thrown if file is found on the path at runtime.  Exception message links to a wiki page with instructions on how to configure the application instance.
Closes #839 
Also note the wiki page  has been created.
https://github.com/ESAPI/esapi-java-legacy/wiki/Configuring-the-JavaLogFactory
=> Issue #839 JavaLogFactory ConcMod

documentation/esapi4java-core-2.6.1.0-release-notes.txt, scripts/vars.2.6.1.0
This was to fix up things to reflect reality and was needed since Maven Central took a bit longer than anticipated the last time.
@xeno6696 / @jeremiahjstacey - Note that there will shortly be a 2nd PR following this on a 2.6.2.0 branch as per the usual process.
=> Fix guessed release date for 2.6.1.0 to its actual release date.
